### ISSUE TITLE
Newline missing when selecting whole line

### ISSUE THREAD

**Issue by Tadaboody** [sohibegit/vscode-java-code-generator#1]
When selecting the properties likes this
<img width="422" alt="screen shot 2018-06-11 at 23 01 49" src="https://user-images.githubusercontent.com/6463334/41254229-977a0926-6dcb-11e8-9559-55089110a4dc.png">
there isn't a newline before the first getter.
But when selecting them like this
<img width="471" alt="screen shot 2018-06-11 at 23 04 22" src="https://user-images.githubusercontent.com/6463334/41254310-d059db54-6dcb-11e8-81a7-ff705efe8820.png">
The newline appears fine

**Comment by sohibegit** [comment]
@Tadaboody thank you this should be fixed in v2.0.0
