### ISSUE TITLE
Support for Hungarian Notation

### ISSUE THREAD

**Issue by dougcooper** [sohibegit/vscode-java-code-generator#12]
Property names such as "_property" or "m_property" result in a getter name of "get_property" and "getM_property" respectively. Ideally both would still produce the name "getProperty".

**Comment by sohibegit** [comment]
@dougcooper thank you but it's better to stick with the JavaBean naming conventions.

Oracle:
> Except for variables, all instance, class, and class constants are in mixed case with a lowercase first letter. Internal words start with capital letters. Variable names should not start with underscore _ or dollar sign $ characters, even though both are allowed.
[https://www.oracle.com/technetwork/java/javase/documentation/codeconventions-135099.html#367](url)

**Comment by dougcooper** [comment]
Hi. Don't mean to seem argumentative but are you suggesting people should change their coding style? I mean the paragraph does say underscores are allowed. Nice plugin and thank you anyways.

**Comment by sohibegit** [comment]
@dougcooper Thank you I'm glad you liked it. Could you please check this one of many articles I came across talking about avoiding Hungarian Notation:
[a-case-against-the-hungarian-notation-on-android](http://zenandroid.io/a-case-against-the-hungarian-notation-on-android/)
if you still need this feature anyway I'll be happy to reopen this issue and add the support for you.

**Comment by dougcooper** [comment]
It’s all good. I actually didn’t realize their was a debate on the matter. While reading that article I realized the habit came from writing c++. After reading googles coding style on c++ I think I will do away with it. Cheers!

**Comment by nickveliki** [comment]
I think it would be nice, since I got in the habit of using leading unders and dunders for python, where it IS convention to use them. Switching between conventions is just a mental effort I'd like to use in a more productive manner
