### ISSUE TITLE
Generator GUI -  constructor using fields not returning 

### ISSUE THREAD

**Issue by HamzaAnis** [sohibegit/vscode-java-code-generator#15]
# Issue
The Constructor with no parameters selected should give empty constructor but it is generating wrong code, altough there is an option to generate empty constructor seperately but this option with no fields should raise an error or create an empty constructor.

# How to regenerate.
A simple java class
```
public class Module {
    String first;
    String second;
    String third;
}
```

1. Open Generator GUI
2. Unselect all fields 
3. Select `Constructor using fields`

The generated code pattern will be like this

```
    public Modul) {
    }
```
where the last character in the name of the class is replaced by `)`.

**Comment by sohibegit** [comment]
thank you it's fixed in v4.1.1
