### ISSUE TITLE
Automatically create class by Filename and package

### ISSUE THREAD

**Issue by DoganM95** [sohibegit/vscode-java-code-generator#18]
HI,

it would be nice, if the extension could automatically create a class inside the .java file with the filename as class-name and automatically set the package.

ideally via a button in the right-click context menu, as some people may not want this to automatically happen.

**Comment by tiagoanleite** [comment]
There's already a code snippet by default on the [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) called `class` that does what you're trying to achieve

**Comment by sohibegit** [comment]
@tiagoanleite solution is correct and solves the issue.
