### ISSUE TITLE
Add "super()" to constructor when it is a child class

### ISSUE THREAD

**Issue by jaaviercr** [sohibegit/vscode-java-code-generator#19]
It would be cool that the constructor would add the call to super() when it its a child class.

**Comment by sohibegit** [comment]
download the [Java Extenstion Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) and you can override from superclass by choosing:
source actions -> generate constructors

**Comment by Chealer** [comment]
I do not get that action offered in VS Code 1.90 (extension pack 0.27.0).
