### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rajashekar** [sohibegit/vscode-java-code-generator#21]
- Issue Type: `Performance`
- Extension Name: `java-generate-setters-getters`
- Extension Version: `4.2.2`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.38.0`

[sohibe.java-generate-setters-getters-unresponsive.cpuprofile.txt](https://github.com/sohibegit/vscode-java-code-generator/files/3577947/sohibe.java-generate-setters-getters-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by sohibegit** [comment]
Do you still have the issue?

**Comment by sohibegit** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the latest version.

Thank you!
