### ISSUE TITLE
Generate constructor using all final fields into context menu 

### ISSUE THREAD

**Issue by DavidCoq** [sohibegit/vscode-java-code-generator#24]
Hi,
I have try to use "Generate constructor using all final fields" into context menu, but doesn't work.
Or rather the function create a empty constructor.

**Comment by sohibegit** [comment]
example please

**Comment by rajinder-yadav** [comment]
Also getting an empty ctor!

```java

public class Person {

  private String name;
  private String surname;
  private int age;

}
