### ISSUE TITLE
Feature request: Option to copy @JsonProperty annotations

### ISSUE THREAD

**Issue by icopp** [sohibegit/vscode-java-code-generator#26]
If enabled, this would copy `@JsonProperty` annotations from variables to getters/setters.

For example:

```java
@JsonProperty("vid")
private Integer visitorId;

@JsonProperty("vid")
public Integer getVisitorId() {
  return visitorId;
}

@JsonProperty("vid")
public void setVisitorId(Integer visitorId) {
  this.visitorId = visitorId;
}
```

This should be an option rather than a default because it's only necessary for some library versions.

It would be up to the user to add the import for the annotation.

**Comment by sohibegit** [comment]
Sure I'll add it for you and thanks for the donation I really appreciate it.
