### ISSUE TITLE
Sohibe code generator no longer working 

### ISSUE THREAD

**Issue by pconrad** [sohibegit/vscode-java-code-generator#35]
I've taught the Sohibe code generators for Java in my Java courses at UC Santa Barbara for over a year now.

They suddenly stopped working for me sometime between December and now.   It may have been the 7.0.0 release, I'm not sure.

The symptom is simple: I install the extension, but the menus that I'm used to seeing when I right click in a Java file simply aren't there:

![image](https://user-images.githubusercontent.com/1119017/108561378-04318a00-72b3-11eb-97ab-34274062e3eb.png)

The extensions is installed, but nothing works

![image](https://user-images.githubusercontent.com/1119017/108561421-18758700-72b3-11eb-8022-796737ed94f3.png)

I don't even know where to begin with trying to determine what is wrong.  I really miss the functionality.

I made a token monetary donation to the project as a show of good faith.

**Comment by sohibegit** [comment]
Thank you for the donation, can you please update to v7.0.2 and tell me if you still have an issue.

**Comment by dderevjanik** [comment]
Hi @sohibegit , I'm having same problem with non-responding code generator. v7.0.2. 
It stopped working sometime last week :/ 

Edit: I tried to install v7.0.0 and it seems it works again 👍

**Comment by pconrad** [comment]
Unfortunately, yes.

If you'd like to hop on a zoom call I can show you what's happening.

I did try uninstall / reinstall as well as shut down VSCode, and restart
VSCode...

-- 
--
Phill Conrad, Teaching Professor, Dept. of Computer Science
University of California, Santa Barbara
Joint Appointment: College of Creative Studies (www.ccs.ucsb.edu)
***@***.***, www.cs.ucsb.edu/~pconrad   Pronouns: he/him/his

**Comment by pconrad** [comment]
Ah... I fixed it.  The problem was that I needed to not only upgrade the
extension, but also I needed to upgrade VSCode itself.

Now all is well.


-- 
--
Phill Conrad, Teaching Professor, Dept. of Computer Science
University of California, Santa Barbara
Joint Appointment: College of Creative Studies (www.ccs.ucsb.edu)
***@***.***, www.cs.ucsb.edu/~pconrad   Pronouns: he/him/his
