### ISSUE TITLE
Override methods from superclass

### ISSUE THREAD

**Issue by tmh2211** [sohibegit/vscode-java-code-generator#4]
It would be cool to be able to generate constructors from super class (like in eclipse) or generate code for methods to override in general.

**Comment by sohibegit** [comment]
yes it would be very cool but for now we can't as this extension works only by string manipulation.

**Comment by sohibegit** [comment]
download the [Java Extenstion Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) and you can override from superclass by choosing:
source actions -> generate constructors
