### ISSUE TITLE
Generate Getters duplicate with boolean property

### ISSUE THREAD

**Issue by thang1160** [sohibegit/vscode-java-code-generator#40]
as you can see, my variable name is `is_pinned`. It would be better if `isIs_pinned` only have 1 `is` (ie: isPinned)

![image](https://user-images.githubusercontent.com/35557579/117861245-6cdd4100-b2bb-11eb-8917-fb0501cfb741.png)

**Comment by thang1160** [comment]
`isPinned` was a terrible idea, Hibernate can't recognize it:
```
Caused by: org.hibernate.PropertyNotFoundException: Could not locate setter method for property [fpt.saplab.sciencemanagementandinternationalaffairsresearcher.model.Article#pinned]
```
`getIs_pinned` and `Is_pinned` works well, also with `isIs_pinned` 😂

**Comment by igortavtib** [comment]
Why are you using snake case in Java?

**Comment by sohibegit** [comment]
name the variable to just `pinned` and let the generator append `is` to it.
also we follow Java Naming Conventions, Java follows camel-case syntax for naming the class, interface, method, and variable.
