### ISSUE TITLE
An error is reported when the enumeration class uses the generator

### ISSUE THREAD

**Issue by wangxiaojuan** [sohibegit/vscode-java-code-generator#43]
![image](https://user-images.githubusercontent.com/1762334/121337985-aa32fe00-c94f-11eb-9aa7-691c9e69a115.png)
Error：
![image](https://user-images.githubusercontent.com/1762334/121338231-e36b6e00-c94f-11eb-9f19-1bd951ca4b2b.png)

**Comment by sohibegit** [comment]
does not work with enums.
