### ISSUE TITLE
Require this in getters

### ISSUE THREAD

**Issue by haykam821** [sohibegit/vscode-java-code-generator#47]
I would prefer the usage of `this` in getter code generation:

```java
public int getWidth() {
    return this.width;
}
```

Could this be an option?

**Comment by pitris90** [comment]
I dont know, but it generates my getters with "this" and I would prefer getter without "this" :D Maybe there could be some option to turn on or off "this" in getters?

**Comment by sohibegit** [comment]
for best practices it's not preferred in normal getters.

**Comment by 0x3C50** [comment]
> for best practices it's not preferred in normal getters.

there is no set "best practice" for getters and setters, but I'd say it would make it clearer where that variable came from. Especially glancing over the thing without knowing exactly which fields are in the class, it'd be very helpful to at least know that the field being gotten belongs to `this`.
