### ISSUE TITLE
Creating constructor does not work

### ISSUE THREAD

**Issue by jhonnytown** [sohibegit/vscode-java-code-generator#51]
Wanted to create a constructor for a class, but it missed the last character of the class name and the opening bracket
I am using VS Code 1.66.1 on Windows 10

Example Code:
```
public class SplashScreen extends GameScreen {

    public SplashScree) {
    }
    
}
```

Additional Info: only happens when there are no attributes in the class and i use "Generate Constructor Using All Fields"

**Comment by sohibegit** [comment]
fixed with v 8.0.0
