### ISSUE TITLE
Enhancement: toString() without getters

### ISSUE THREAD

**Issue by scotshall** [sohibegit/vscode-java-code-generator#7]
Greetings,

If possible, please provide an option to generate toString() methods by accessing the fields directly instead of using getter methods.

**Comment by egoarka** [comment]
Nice idea, but how it will appear in the context menu?
There's already `Generate toString()` command.

or it would be cool to use a nested context menu

![fc88b4ce-482b-4a44-b1ae-f8608a469a79](https://user-images.githubusercontent.com/29709538/49500807-955ae880-f882-11e8-9a2e-7b74ca5a7408.png)

**Comment by scotshall** [comment]
A new user setting to toggle between the settings would work for me.
